//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BASEDBEntities : DbContext
    {
        public BASEDBEntities()
            : base("name=BASEDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<entrada> entrada { get; set; }
        public virtual DbSet<inventory> inventory { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<stock> stock { get; set; }

    }
}
