//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int Id { get; set; }
        public int producto { get; set; }
        public int cantidad { get; set; }
        public int id_admin { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Admins Admins { get; set; }
        public virtual product product { get; set; }
    }
}
